"""Business logic and service layer package."""

from app.services.auth_service import (
    authenticate_user,
    generate_user_token,
    get_user_by_email,
    get_user_by_id,
    get_user_by_username,
    register_user,
)
from app.services.category_service import (
    create_category,
    delete_category,
    get_categories,
    get_category_by_id,
    get_category_by_name,
    update_category,
)
from app.services.forecast_service import (
    archive_previous_forecasts,
    build_forecast_explanation,
    calculate_sma,
    calculate_wma,
    generate_all_forecasts,
    generate_forecast_dates,
    generate_product_forecast,
    get_daily_sales_history,
    get_forecast,
    get_forecasts,
    get_product_latest_forecast,
)
from app.services.inventory_service import (
    apply_stock_in,
    apply_stock_out,
    calculate_inventory_status,
    get_inventory_by_product_id,
    get_inventory_list,
    get_or_create_inventory,
    get_transaction_by_id,
    get_transactions,
    perform_stock_adjustment,
    perform_stock_in,
    perform_stock_out,
)
from app.services.product_service import (
    create_product,
    delete_product,
    get_product_by_id,
    get_product_by_sku,
    get_products,
    update_product,
)
from app.services.purchase_order_service import (
    create_purchase_order,
    generate_order_number,
    get_purchase_order_by_id,
    get_purchase_orders,
    receive_purchase_order,
    update_purchase_order,
    update_purchase_order_status,
)
from app.services.replenishment_service import (
    build_replenishment_reason,
    calculate_average_daily_demand,
    calculate_base_target,
    calculate_inventory_position,
    calculate_lead_time_demand,
    calculate_priority,
    calculate_recommended_quantity,
    dismiss_recommendation,
    evaluate_product_replenishment,
    generate_recommendations,
    get_recommendation_by_id,
    get_recommendations,
    review_recommendation,
)
from app.services.sales_service import create_sale, get_sale_by_id, get_sales
from app.services.supplier_service import (
    create_supplier,
    delete_supplier,
    get_supplier_by_id,
    get_suppliers,
    update_supplier,
)

__all__ = [
    # Auth
    "register_user",
    "authenticate_user",
    "generate_user_token",
    "get_user_by_id",
    "get_user_by_username",
    "get_user_by_email",
    # Category
    "get_category_by_id",
    "get_category_by_name",
    "get_categories",
    "create_category",
    "update_category",
    "delete_category",
    # Supplier
    "get_supplier_by_id",
    "get_suppliers",
    "create_supplier",
    "update_supplier",
    "delete_supplier",
    # Product
    "get_product_by_id",
    "get_product_by_sku",
    "get_products",
    "create_product",
    "update_product",
    "delete_product",
    # Inventory
    "calculate_inventory_status",
    "get_or_create_inventory",
    "apply_stock_in",
    "apply_stock_out",
    "perform_stock_in",
    "perform_stock_out",
    "perform_stock_adjustment",
    "get_inventory_by_product_id",
    "get_inventory_list",
    "get_transactions",
    "get_transaction_by_id",
    # Sales
    "create_sale",
    "get_sale_by_id",
    "get_sales",
    # Purchase Orders
    "generate_order_number",
    "create_purchase_order",
    "get_purchase_order_by_id",
    "get_purchase_orders",
    "update_purchase_order",
    "update_purchase_order_status",
    "receive_purchase_order",
    # Replenishment
    "calculate_inventory_position",
    "calculate_average_daily_demand",
    "calculate_lead_time_demand",
    "calculate_base_target",
    "calculate_recommended_quantity",
    "calculate_priority",
    "build_replenishment_reason",
    "evaluate_product_replenishment",
    "generate_recommendations",
    "get_recommendation_by_id",
    "get_recommendations",
    "review_recommendation",
    "dismiss_recommendation",
    # Demand Forecasting
    "get_daily_sales_history",
    "calculate_sma",
    "calculate_wma",
    "build_forecast_explanation",
    "generate_forecast_dates",
    "archive_previous_forecasts",
    "generate_product_forecast",
    "generate_all_forecasts",
    "get_forecast",
    "get_product_latest_forecast",
    "get_forecasts",
]
